/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCommitteesIndexRouteImport } from './routes/_dashboard/committees/index'
import { Route as DashboardExpenseCategoriesIndexRouteImport } from './routes/_dashboard/expense-categories/index'
import { Route as DashboardFiscalYearIndexRouteImport } from './routes/_dashboard/fiscal-year/index'
import { Route as DashboardIncomeIndexRouteImport } from './routes/_dashboard/income/index'
import { Route as DashboardOrganizationIndexRouteImport } from './routes/_dashboard/organization/index'
import { Route as DashboardReceiptBooksIndexRouteImport } from './routes/_dashboard/receipt-books/index'
import { Route as DashboardUserIndexRouteImport } from './routes/_dashboard/user/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCommitteesIndexRoute =
  DashboardCommitteesIndexRouteImport.update({
    id: '/committees/',
    path: '/committees/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardExpenseCategoriesIndexRoute =
  DashboardExpenseCategoriesIndexRouteImport.update({
    id: '/expense-categories/',
    path: '/expense-categories/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardFiscalYearIndexRoute =
  DashboardFiscalYearIndexRouteImport.update({
    id: '/fiscal-year/',
    path: '/fiscal-year/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardIncomeIndexRoute = DashboardIncomeIndexRouteImport.update({
  id: '/income/',
  path: '/income/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrganizationIndexRoute =
  DashboardOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReceiptBooksIndexRoute =
  DashboardReceiptBooksIndexRouteImport.update({
    id: '/receipt-books/',
    path: '/receipt-books/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUserIndexRoute = DashboardUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/committees/': typeof DashboardCommitteesIndexRoute
  '/expense-categories/': typeof DashboardExpenseCategoriesIndexRoute
  '/fiscal-year/': typeof DashboardFiscalYearIndexRoute
  '/income/': typeof DashboardIncomeIndexRoute
  '/organization/': typeof DashboardOrganizationIndexRoute
  '/receipt-books/': typeof DashboardReceiptBooksIndexRoute
  '/user/': typeof DashboardUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/committees': typeof DashboardCommitteesIndexRoute
  '/expense-categories': typeof DashboardExpenseCategoriesIndexRoute
  '/fiscal-year': typeof DashboardFiscalYearIndexRoute
  '/income': typeof DashboardIncomeIndexRoute
  '/organization': typeof DashboardOrganizationIndexRoute
  '/receipt-books': typeof DashboardReceiptBooksIndexRoute
  '/user': typeof DashboardUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/committees/': typeof DashboardCommitteesIndexRoute
  '/_dashboard/expense-categories/': typeof DashboardExpenseCategoriesIndexRoute
  '/_dashboard/fiscal-year/': typeof DashboardFiscalYearIndexRoute
  '/_dashboard/income/': typeof DashboardIncomeIndexRoute
  '/_dashboard/organization/': typeof DashboardOrganizationIndexRoute
  '/_dashboard/receipt-books/': typeof DashboardReceiptBooksIndexRoute
  '/_dashboard/user/': typeof DashboardUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/committees/'
    | '/expense-categories/'
    | '/fiscal-year/'
    | '/income/'
    | '/organization/'
    | '/receipt-books/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/committees'
    | '/expense-categories'
    | '/fiscal-year'
    | '/income'
    | '/organization'
    | '/receipt-books'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_auth/login'
    | '/_dashboard/dashboard'
    | '/_dashboard/committees/'
    | '/_dashboard/expense-categories/'
    | '/_dashboard/fiscal-year/'
    | '/_dashboard/income/'
    | '/_dashboard/organization/'
    | '/_dashboard/receipt-books/'
    | '/_dashboard/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/committees/': {
      id: '/_dashboard/committees/'
      path: '/committees'
      fullPath: '/committees/'
      preLoaderRoute: typeof DashboardCommitteesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/expense-categories/': {
      id: '/_dashboard/expense-categories/'
      path: '/expense-categories'
      fullPath: '/expense-categories/'
      preLoaderRoute: typeof DashboardExpenseCategoriesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/fiscal-year/': {
      id: '/_dashboard/fiscal-year/'
      path: '/fiscal-year'
      fullPath: '/fiscal-year/'
      preLoaderRoute: typeof DashboardFiscalYearIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/income/': {
      id: '/_dashboard/income/'
      path: '/income'
      fullPath: '/income/'
      preLoaderRoute: typeof DashboardIncomeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/organization/': {
      id: '/_dashboard/organization/'
      path: '/organization'
      fullPath: '/organization/'
      preLoaderRoute: typeof DashboardOrganizationIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/receipt-books/': {
      id: '/_dashboard/receipt-books/'
      path: '/receipt-books'
      fullPath: '/receipt-books/'
      preLoaderRoute: typeof DashboardReceiptBooksIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/user/': {
      id: '/_dashboard/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof DashboardUserIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardCommitteesIndexRoute: typeof DashboardCommitteesIndexRoute
  DashboardExpenseCategoriesIndexRoute: typeof DashboardExpenseCategoriesIndexRoute
  DashboardFiscalYearIndexRoute: typeof DashboardFiscalYearIndexRoute
  DashboardIncomeIndexRoute: typeof DashboardIncomeIndexRoute
  DashboardOrganizationIndexRoute: typeof DashboardOrganizationIndexRoute
  DashboardReceiptBooksIndexRoute: typeof DashboardReceiptBooksIndexRoute
  DashboardUserIndexRoute: typeof DashboardUserIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardCommitteesIndexRoute: DashboardCommitteesIndexRoute,
  DashboardExpenseCategoriesIndexRoute: DashboardExpenseCategoriesIndexRoute,
  DashboardFiscalYearIndexRoute: DashboardFiscalYearIndexRoute,
  DashboardIncomeIndexRoute: DashboardIncomeIndexRoute,
  DashboardOrganizationIndexRoute: DashboardOrganizationIndexRoute,
  DashboardReceiptBooksIndexRoute: DashboardReceiptBooksIndexRoute,
  DashboardUserIndexRoute: DashboardUserIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
