export const QUERY_KEYS = {
  INCOME: "INCOME",
  ADD_INCOME: "ADD_INCOME",
  EXPENSE: "EXPENSE",
  ADD_EXPENSE: "ADD_EXPENSE",
  RECEIPT_BOOK: "RECEIPT_BOOK",
  ADD_RECEIPT_BOOK: "ADD_RECEIPT_BOOK",
  FISCAL_YEAR: "FISCAL_YEAR",
  ADD_FISCAL_YEAR: "ADD_FISCAL_YEAR",
  ASSIGN_BOOK: "ASSIGN_BOOK",
  RETURN_BOOK: "RETURN_BOOK",
} as const;

export type QueryKeys = (typeof QUERY_KEYS)[keyof typeof QUERY_KEYS];
